k8s_namespace: "unir"
directorio_trabajo: "/tmp"
aplicacion:
  definicion: "aks1-deployment.yaml"
  politica_renicio: OnFailure
  adminer:
    nombre: adminer
    imagen:
      nombre: adminer
      tag: 4.8.1
      carpeta_destino: carpeta-adminer
    replicas: 1
    recursos:
      cpu: 100m
      memoria: 128Mi
    limites:
      cpu: 250m
      memoria: 256Mi
    puertoContenedor: 8080
    puertoEntrada: 80
  mysql:
    nombre: mysql
    imagen:
      nombre: mariadb
      tag: 10.7.8
      carpeta_destino: carpeta-mysql
    replicas: 1
    recursos:
      cpu: 100m
      memoria: 128Mi
    limites:
      cpu: 250m
      memoria: 256Mi
    puerto: 3306
    env:
      database: unir
      user: unir
      password: unir
      root_password: unir
      allow_empty_password: true
    pv_claim:
      nombre: mysql-pv-claim
      nombre_volumen: mysql-persistent-storage
      espacio: 5Gi
