---
# playbook para la linux vm

- name: 'VM - Aplicación Web'
  hosts: vm1
  remote_user: azureuser
  become: true
  vars_files:
     - vars/private_vars.yaml
     - vars/common_vars.yaml
     - vars/vm1_vars.yaml
  tasks:

    - name: 'Actualizar la zona horaria'
      timezone:
        name: "{{ timezone }}"

    - name: 'Actualizar todos los paquetes instalados'
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: 'Instalar los paquetes que necesitamos'
      yum:
        name: "{{ packages_to_install }}" 
        state: latest

    - name: Identificarnos en nuestro Azure container registry y creamos ${XDG_RUNTIME_DIR}/containers/auth.json
      containers.podman.podman_login:
        registry: "{{ cr_registry }}"
        username: "{{ cr_username }}"
        password: "{{ cr_password }}"

    - name: Pull la imagen symfony-demo:casopractico2
      containers.podman.podman_image:
        name: "{{ cr_registry }}/{{ img_name_sf_demo }}"
        tag: "{{ img_tag_name_cp2 }}"

    - name: Iniciar contenedor con la imagen symfony-demo:casopractico2 y crear un servicio para systemd
      containers.podman.podman_container:
        name: "{{ img_name_sf_demo }}"
        image: "{{ img_name_sf_demo }}:{{ img_tag_name_cp2 }}"
        detach: true
        expose:
          - 443
        publish:
          - 443:443
        state: created
        generate_systemd:
          path: /etc/systemd/system/
          restart_policy: on-failure
          time: 120
          names: true

    - name: Activar y iniciar container-symfony-demo.service
      ansible.builtin.systemd:
        name: "container-{{ img_name_sf_demo }}.service"
        enabled: true
        state: started

    # TODO: Enable firewall?
