---
# playbook para la linux vm

- name: 'VM - Aplicación Web'
  hosts: vm1
  remote_user: azureuser
  become: true
  vars_files:
     - vars/azure_container_registry_vars.yaml
     - vars/vm1_vars.yaml
  tasks:
    # TODO: Enable firewall

    - name: 'Actualizar la zona horaria'
      timezone:
        name: "{{ timezone }}"

    - name: 'Actualizar todos los paquetes instalados'
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: 'Instalar los paquetes que necesitamos'
      yum:
        name: "{{ packages_to_install }}" 
        state: latest

    - name: Identificarnos en nuestro Azure container registry y creamos ${XDG_RUNTIME_DIR}/containers/auth.json
      containers.podman.podman_login:
        registry: "{{ cr_registry }}"
        username: "{{ cr_username }}"
        password: "{{ cr_password }}"

    - name: Prueba - copiar template
      template:
        src: files/index.php.j2
        dest: "~/index.php"
        # owner: bin
        # group: wheel
        # mode: '0644'
