# playbook para el cluster de k8s

- name: 'Despliegue de AKS'
  hosts: localhost
  environment:
    K8S_AUTH_KUBECONFIG: "vars/.kubeconfig"
  vars_files:
     - vars/aks1_vars.yaml
  tasks:

    - name: 'Definir los objectos deployment y servicios'
      template:
        src: "templates/aks1-deployment.j2"
        dest: "{{ directorio_trabajo }}/{{ aplicacion.definicion }}"

    - name: 'Crear el namespace de trabajo'
      kubernetes.core.k8s:
        kind: Namespace
        name: "{{ k8s_namespace }}"

    - name: 'Crear Deployments y servicios de la aplicación'
      kubernetes.core.k8s:
        state: present
        #state: absent
        template: "{{ directorio_trabajo }}/{{ aplicacion.definicion }}"

#    - name: Prueba - copiar template
#      template:
#        src: files/index.php.j2
#        dest: "~/index.php"
#        # owner: bin
#        # group: wheel
#        # mode: '0644'
